<?php

// Brand configurations for Link in Bio buttons
return [
    'platforms' => [
        // Major Social
        'facebook' => [
            'name' => 'Facebook',
            'icon' => 'facebook.svg',
            'color' => '#0866FF',
            'text' => '#ffffff',
            'placeholder' => 'https://facebook.com/username',
            'category' => 'social',
        ],
        'instagram' => [
            'name' => 'Instagram',
            'icon' => 'instagram.svg',
            'color' => '#E4405F',
            'text' => '#ffffff',
            'placeholder' => '@username',
            'category' => 'social',
        ],
        'x' => [
            'name' => 'X (Twitter)',
            'icon' => 'x.svg',
            'color' => '#000000',
            'text' => '#ffffff',
            'border' => '#ffffff',
            'placeholder' => '@username',
            'category' => 'social',
        ],
        'threads' => [
            'name' => 'Threads',
            'icon' => 'threads.svg',
            'color' => '#000000',
            'text' => '#ffffff',
            'border' => '#ffffff',
            'placeholder' => '@username',
            'category' => 'social',
        ],
        'tiktok' => [
            'name' => 'TikTok',
            'icon' => 'tiktok.svg',
            'color' => '#000000',
            'text' => '#ffffff',
            'placeholder' => '@username',
            'category' => 'social',
        ],
        'youtube' => [
            'name' => 'YouTube',
            'icon' => 'youtube.svg',
            'color' => '#FF0000',
            'text' => '#ffffff',
            'placeholder' => 'youtube.com/@channel or youtu.be/VIDEO',
            'category' => 'social',
        ],
        'youtube-music' => [
            'name' => 'YouTube Music',
            'icon' => 'youtube-music.svg',
            'color' => '#FF0000',
            'text' => '#ffffff',
            'placeholder' => 'https://music.youtube.com/...',
            'category' => 'music',
        ],
        'linkedin' => [
            'name' => 'LinkedIn',
            'icon' => 'linkedin.svg',
            'color' => '#0A66C2',
            'text' => '#ffffff',
            'placeholder' => 'https://linkedin.com/in/profile',
            'category' => 'social',
        ],
        'pinterest' => [
            'name' => 'Pinterest',
            'icon' => 'pinterest.svg',
            'color' => '#BD081C',
            'text' => '#ffffff',
            'placeholder' => 'https://pinterest.com/username',
            'category' => 'social',
        ],
        'snapchat' => [
            'name' => 'Snapchat',
            'icon' => 'snapchat.svg',
            'color' => '#FFFC00',
            'text' => '#000000',
            'placeholder' => '@username or snapchat.com/add/username',
            'category' => 'social',
        ],
        'reddit' => [
            'name' => 'Reddit',
            'icon' => 'reddit.svg',
            'color' => '#FF4500',
            'text' => '#ffffff',
            'placeholder' => 'https://reddit.com/u/username',
            'category' => 'social',
        ],
        'tumblr' => [
            'name' => 'Tumblr',
            'icon' => 'tumblr.svg',
            'color' => '#36465D',
            'text' => '#ffffff',
            'placeholder' => 'https://username.tumblr.com',
            'category' => 'social',
        ],
        'bluesky' => [
            'name' => 'Bluesky',
            'icon' => 'bluesky.svg',
            'color' => '#1185FE',
            'text' => '#ffffff',
            'placeholder' => '@handle or bsky.app/profile/handle',
            'category' => 'social',
        ],
        'mastodon' => [
            'name' => 'Mastodon',
            'icon' => 'mastodon.svg',
            'color' => '#6364FF',
            'text' => '#ffffff',
            'placeholder' => '@user@instance.social',
            'category' => 'social',
        ],
        // Messaging
        'whatsapp' => [
            'name' => 'WhatsApp',
            'icon' => 'whatsapp.svg',
            'color' => '#25D366',
            'text' => '#ffffff',
            'placeholder' => '+1234567890 (with country code)',
            'category' => 'messaging',
        ],
        'telegram' => [
            'name' => 'Telegram',
            'icon' => 'telegram.svg',
            'color' => '#26A5E4',
            'text' => '#ffffff',
            'placeholder' => 't.me/username',
            'category' => 'messaging',
        ],
        'messenger' => [
            'name' => 'Messenger',
            'icon' => 'messenger.svg',
            'color' => '#0866FF',
            'text' => '#ffffff',
            'placeholder' => 'm.me/username',
            'category' => 'messaging',
        ],
        'discord' => [
            'name' => 'Discord',
            'icon' => 'discord.svg',
            'color' => '#5865F2',
            'text' => '#ffffff',
            'placeholder' => 'invitecode or discord.gg/invitecode',
            'category' => 'messaging',
        ],
        'signal' => [
            'name' => 'Signal',
            'icon' => 'signal.svg',
            'color' => '#3A76F0',
            'text' => '#ffffff',
            'placeholder' => '+1234567890 (with country code)',
            'category' => 'messaging',
        ],
        'line' => [
            'name' => 'LINE',
            'icon' => 'line.svg',
            'color' => '#00B900',
            'text' => '#ffffff',
            'placeholder' => '@lineid',
            'category' => 'messaging',
        ],
        'slack' => [
            'name' => 'Slack',
            'icon' => 'slack.svg',
            'color' => '#4A154B',
            'text' => '#ffffff',
            'placeholder' => 'workspace.slack.com',
            'category' => 'messaging',
        ],
        // Music & Podcast
        'spotify' => [
            'name' => 'Spotify',
            'icon' => 'spotify.svg',
            'color' => '#1DB954',
            'text' => '#ffffff',
            'placeholder' => 'open.spotify.com/...',
            'category' => 'music',
        ],
        'apple-music' => [
            'name' => 'Apple Music',
            'icon' => 'apple-music.svg',
            'color' => '#000000',
            'text' => '#ffffff',
            'border' => '#ffffff',
            'placeholder' => 'music.apple.com/...',
            'category' => 'music',
        ],
        'apple-podcasts' => [
            'name' => 'Apple Podcasts',
            'icon' => 'apple-podcasts.svg',
            'color' => '#000000',
            'text' => '#ffffff',
            'border' => '#ffffff',
            'placeholder' => 'podcasts.apple.com/...',
            'category' => 'music',
        ],
        'amazon-music' => [
            'name' => 'Amazon Music',
            'icon' => 'amazon-music.svg',
            'color' => '#25D1DA',
            'text' => '#000000',
            'placeholder' => 'music.amazon.com/...',
            'category' => 'music',
        ],
        'soundcloud' => [
            'name' => 'SoundCloud',
            'icon' => 'soundcloud.svg',
            'color' => '#FF5500',
            'text' => '#ffffff',
            'placeholder' => 'soundcloud.com/username',
            'category' => 'music',
        ],
        'bandcamp' => [
            'name' => 'Bandcamp',
            'icon' => 'bandcamp.svg',
            'color' => '#1DA0C3',
            'text' => '#ffffff',
            'placeholder' => 'username.bandcamp.com',
            'category' => 'music',
        ],
        // Video & Streaming
        'twitch' => [
            'name' => 'Twitch',
            'icon' => 'twitch.svg',
            'color' => '#9146FF',
            'text' => '#ffffff',
            'placeholder' => 'twitch.tv/username',
            'category' => 'video',
        ],
        'kick' => [
            'name' => 'Kick',
            'icon' => 'kick.svg',
            'color' => '#53FC18',
            'text' => '#000000',
            'placeholder' => 'kick.com/username',
            'category' => 'video',
        ],
        'vimeo' => [
            'name' => 'Vimeo',
            'icon' => 'vimeo.svg',
            'color' => '#1AB7EA',
            'text' => '#ffffff',
            'placeholder' => 'vimeo.com/username',
            'category' => 'video',
        ],
        // Developer
        'github' => [
            'name' => 'GitHub',
            'icon' => 'github.svg',
            'color' => '#181717',
            'text' => '#ffffff',
            'placeholder' => 'github.com/username',
            'category' => 'developer',
        ],
        'gitlab' => [
            'name' => 'GitLab',
            'icon' => 'gitlab.svg',
            'color' => '#FC6D26',
            'text' => '#ffffff',
            'placeholder' => 'gitlab.com/username',
            'category' => 'developer',
        ],
        'dev-to' => [
            'name' => 'DEV.to',
            'icon' => 'dev-to.svg',
            'color' => '#0A0A0A',
            'text' => '#ffffff',
            'placeholder' => 'dev.to/username',
            'category' => 'developer',
        ],
        'stack-overflow' => [
            'name' => 'Stack Overflow',
            'icon' => 'stack-overflow.svg',
            'color' => '#F58025',
            'text' => '#ffffff',
            'placeholder' => 'stackoverflow.com/users/...',
            'category' => 'developer',
        ],
        'hashnode' => [
            'name' => 'Hashnode',
            'icon' => 'hashnode.svg',
            'color' => '#2962FF',
            'text' => '#ffffff',
            'placeholder' => 'hashnode.com/@username',
            'category' => 'developer',
        ],
        'medium' => [
            'name' => 'Medium',
            'icon' => 'medium.svg',
            'color' => '#000000',
            'text' => '#ffffff',
            'placeholder' => 'medium.com/@username',
            'category' => 'developer',
        ],
        'substack' => [
            'name' => 'Substack',
            'icon' => 'substack.svg',
            'color' => '#FF6719',
            'text' => '#ffffff',
            'placeholder' => 'username.substack.com',
            'category' => 'developer',
        ],
        // Design
        'dribbble' => [
            'name' => 'Dribbble',
            'icon' => 'dribbble.svg',
            'color' => '#EA4C89',
            'text' => '#ffffff',
            'placeholder' => 'dribbble.com/username',
            'category' => 'design',
        ],
        'behance' => [
            'name' => 'Behance',
            'icon' => 'behance.svg',
            'color' => '#0057FF',
            'text' => '#ffffff',
            'placeholder' => 'behance.net/username',
            'category' => 'design',
        ],
        'figma' => [
            'name' => 'Figma',
            'icon' => 'figma.svg',
            'color' => '#F24E1E',
            'text' => '#ffffff',
            'placeholder' => 'figma.com/@username',
            'category' => 'design',
        ],
        'artstation' => [
            'name' => 'ArtStation',
            'icon' => 'artstation.svg',
            'color' => '#13AFF0',
            'text' => '#ffffff',
            'placeholder' => 'artstation.com/username',
            'category' => 'design',
        ],
        'unsplash' => [
            'name' => 'Unsplash',
            'icon' => 'unsplash.svg',
            'color' => '#000000',
            'text' => '#ffffff',
            'placeholder' => 'unsplash.com/@username',
            'category' => 'design',
        ],
        'vsco' => [
            'name' => 'VSCO',
            'icon' => 'vsco.svg',
            'color' => '#000000',
            'text' => '#ffffff',
            'placeholder' => 'vsco.co/username',
            'category' => 'design',
        ],
        'flickr' => [
            'name' => 'Flickr',
            'icon' => 'flickr.svg',
            'color' => '#0063DC',
            'text' => '#ffffff',
            'placeholder' => 'flickr.com/photos/username',
            'category' => 'design',
        ],
        // Shopping & Business
        'amazon' => [
            'name' => 'Amazon',
            'icon' => 'amazon.svg',
            'color' => '#FF9900',
            'text' => '#000000',
            'placeholder' => 'amazon.com/shop/...',
            'category' => 'shopping',
        ],
        'etsy' => [
            'name' => 'Etsy',
            'icon' => 'etsy.svg',
            'color' => '#F45800',
            'text' => '#ffffff',
            'placeholder' => 'etsy.com/shop/yourshop',
            'category' => 'shopping',
        ],
        'shop' => [
            'name' => 'Shop',
            'icon' => 'shop.svg',
            'color' => '#5A31F4',
            'text' => '#ffffff',
            'placeholder' => 'Your shop URL',
            'category' => 'shopping',
        ],
        'fiverr' => [
            'name' => 'Fiverr',
            'icon' => 'fiverr.svg',
            'color' => '#1DBF73',
            'text' => '#ffffff',
            'placeholder' => 'fiverr.com/username',
            'category' => 'shopping',
        ],
        // Payment & Support
        'paypal' => [
            'name' => 'PayPal',
            'icon' => 'paypal.svg',
            'color' => '#003087',
            'text' => '#ffffff',
            'placeholder' => 'paypal.me/username',
            'category' => 'payment',
        ],
        'venmo' => [
            'name' => 'Venmo',
            'icon' => 'venmo.svg',
            'color' => '#3D95CE',
            'text' => '#ffffff',
            'placeholder' => '@username or venmo.com/username',
            'category' => 'payment',
        ],
        'cash-app' => [
            'name' => 'Cash App',
            'icon' => 'cash-app-dollar.svg',
            'color' => '#00D64B',
            'text' => '#ffffff',
            'placeholder' => '$cashtag',
            'category' => 'payment',
        ],
        'patreon' => [
            'name' => 'Patreon',
            'icon' => 'patreon.svg',
            'color' => '#FF424D',
            'text' => '#ffffff',
            'placeholder' => 'patreon.com/username',
            'category' => 'payment',
        ],
        'ko-fi' => [
            'name' => 'Ko-fi',
            'icon' => 'ko-fi.svg',
            'color' => '#FF5E5B',
            'text' => '#ffffff',
            'placeholder' => 'ko-fi.com/username',
            'category' => 'payment',
        ],
        'buy-me-a-coffee' => [
            'name' => 'Buy Me a Coffee',
            'icon' => 'buy-me-a-coffee.svg',
            'color' => '#FFDD00',
            'text' => '#000000',
            'placeholder' => 'buymeacoffee.com/username',
            'category' => 'payment',
        ],
        'gofundme' => [
            'name' => 'GoFundMe',
            'icon' => 'gofundme.svg',
            'color' => '#00B964',
            'text' => '#ffffff',
            'placeholder' => 'gofundme.com/f/...',
            'category' => 'payment',
        ],
        'kickstarter' => [
            'name' => 'Kickstarter',
            'icon' => 'kickstarter.svg',
            'color' => '#05CE78',
            'text' => '#ffffff',
            'placeholder' => 'kickstarter.com/projects/...',
            'category' => 'payment',
        ],
        // Productivity
        'notion' => [
            'name' => 'Notion',
            'icon' => 'notion.svg',
            'color' => '#000000',
            'text' => '#ffffff',
            'placeholder' => 'notion.so/...',
            'category' => 'productivity',
        ],
        'trello' => [
            'name' => 'Trello',
            'icon' => 'trello.svg',
            'color' => '#0052CC',
            'text' => '#ffffff',
            'placeholder' => 'trello.com/b/...',
            'category' => 'productivity',
        ],
        'google-drive' => [
            'name' => 'Google Drive',
            'icon' => 'google-drive.svg',
            'color' => '#4285F4',
            'text' => '#ffffff',
            'placeholder' => 'drive.google.com/...',
            'category' => 'productivity',
        ],
        'calendly' => [
            'name' => 'Calendly',
            'icon' => 'calendly.svg',
            'color' => '#006BFF',
            'text' => '#ffffff',
            'placeholder' => 'calendly.com/username',
            'category' => 'productivity',
        ],
        'cal' => [
            'name' => 'Cal.com',
            'icon' => 'cal.svg',
            'color' => '#292929',
            'text' => '#ffffff',
            'placeholder' => 'cal.com/username',
            'category' => 'productivity',
        ],
        'zoom' => [
            'name' => 'Zoom',
            'icon' => 'zoom.svg',
            'color' => '#0B5CFF',
            'text' => '#ffffff',
            'placeholder' => 'zoom.us/j/...',
            'category' => 'productivity',
        ],
        // Entertainment
        'steam' => [
            'name' => 'Steam',
            'icon' => 'steam.svg',
            'color' => '#000000',
            'text' => '#ffffff',
            'placeholder' => 'steamcommunity.com/id/... or store.steampowered.com/app/...',
            'category' => 'gaming',
        ],
        'last-fm' => [
            'name' => 'Last.fm',
            'icon' => 'last-fm.svg',
            'color' => '#D51007',
            'text' => '#ffffff',
            'placeholder' => 'last.fm/user/...',
            'category' => 'music',
        ],
        'letterboxd' => [
            'name' => 'Letterboxd',
            'icon' => 'letterboxd.svg',
            'color' => '#00E054',
            'text' => '#ffffff',
            'placeholder' => 'letterboxd.com/username',
            'category' => 'entertainment',
        ],
        'goodreads' => [
            'name' => 'Goodreads',
            'icon' => 'goodreads.svg',
            'color' => '#553B08',
            'text' => '#ffffff',
            'placeholder' => 'goodreads.com/user/...',
            'category' => 'entertainment',
        ],
        // App Stores
        'appstore' => [
            'name' => 'App Store',
            'icon' => 'apple.svg',
            'color' => '#000000',
            'text' => '#ffffff',
            'border' => '#ffffff',
            'placeholder' => 'apps.apple.com/app/...',
            'category' => 'appstore',
        ],
        'google-play' => [
            'name' => 'Google Play',
            'icon' => 'google-play.svg',
            'color' => '#414141',
            'text' => '#ffffff',
            'placeholder' => 'play.google.com/store/apps/...',
            'category' => 'appstore',
        ],
        // Contact
        'email' => [
            'name' => 'Email',
            'icon' => 'email.svg',
            'color' => '#EA4335',
            'text' => '#ffffff',
            'placeholder' => 'your@email.com',
            'category' => 'contact',
        ],
        'phone' => [
            'name' => 'Phone',
            'icon' => 'generic-phone.svg',
            'color' => '#25D366',
            'text' => '#ffffff',
            'placeholder' => '+1234567890',
            'category' => 'contact',
        ],
        'sms' => [
            'name' => 'SMS',
            'icon' => 'generic-sms.svg',
            'color' => '#25D366',
            'text' => '#ffffff',
            'placeholder' => '+1234567890',
            'category' => 'contact',
        ],
        // Generic
        'website' => [
            'name' => 'Website',
            'icon' => 'generic-website.svg',
            'color' => '#2457F5',
            'text' => '#ffffff',
            'placeholder' => 'https://yourwebsite.com',
            'category' => 'generic',
        ],
        'blog' => [
            'name' => 'Blog',
            'icon' => 'blog.svg',
            'color' => '#FFA500',
            'text' => '#ffffff',
            'placeholder' => 'https://yourblog.com',
            'category' => 'generic',
        ],
        'link' => [
            'name' => 'Link',
            'icon' => 'generic-website.svg',
            'color' => '#6366F1',
            'text' => '#ffffff',
            'placeholder' => 'https://...',
            'category' => 'generic',
        ],
        // Gaming Extended
        'xbox' => [
            'name' => 'Xbox',
            'icon' => 'xbox.svg',
            'color' => '#107C10',
            'text' => '#ffffff',
            'placeholder' => 'xbox.com/profile/...',
            'category' => 'gaming',
        ],
        'playstation' => [
            'name' => 'PlayStation',
            'icon' => 'playstation.svg',
            'color' => '#003791',
            'text' => '#ffffff',
            'placeholder' => 'psnprofiles.com/...',
            'category' => 'gaming',
        ],
        'vrchat' => [
            'name' => 'VRChat',
            'icon' => 'vrchat.svg',
            'color' => '#095d6a',
            'text' => '#ffffff',
            'placeholder' => 'vrchat.com/home/user/...',
            'category' => 'gaming',
        ],
        'osu' => [
            'name' => 'osu!',
            'icon' => 'osu.svg',
            'color' => '#FF66AA',
            'text' => '#ffffff',
            'placeholder' => 'osu.ppy.sh/users/...',
            'category' => 'gaming',
        ],
        'itch-io' => [
            'name' => 'itch.io',
            'icon' => 'itch-io.svg',
            'color' => '#fa5c5c',
            'text' => '#ffffff',
            'placeholder' => 'username.itch.io',
            'category' => 'gaming',
        ],
        'gog' => [
            'name' => 'GOG',
            'icon' => 'gog.svg',
            'color' => '#86328A',
            'text' => '#ffffff',
            'placeholder' => 'gog.com/u/...',
            'category' => 'gaming',
        ],
        'roll20' => [
            'name' => 'Roll20',
            'icon' => 'roll20.svg',
            'color' => '#ce0f22',
            'text' => '#ffffff',
            'placeholder' => 'app.roll20.net/users/...',
            'category' => 'gaming',
        ],
        // Music Extended
        'deezer' => [
            'name' => 'Deezer',
            'icon' => 'deezer.svg',
            'color' => '#FF0092',
            'text' => '#ffffff',
            'placeholder' => 'deezer.com/profile/...',
            'category' => 'music',
        ],
        'tidal' => [
            'name' => 'TIDAL',
            'icon' => 'tidal.svg',
            'color' => '#000000',
            'text' => '#ffffff',
            'placeholder' => 'tidal.com/browse/artist/...',
            'category' => 'music',
        ],
        'qobuz' => [
            'name' => 'Qobuz',
            'icon' => 'qobuz.svg',
            'color' => '#2C8CB8',
            'text' => '#ffffff',
            'placeholder' => 'open.qobuz.com/artist/...',
            'category' => 'music',
        ],
        'mixcloud' => [
            'name' => 'Mixcloud',
            'icon' => 'mixcloud.svg',
            'color' => '#52aad8',
            'text' => '#ffffff',
            'placeholder' => 'mixcloud.com/username',
            'category' => 'music',
        ],
        'audiomack' => [
            'name' => 'Audiomack',
            'icon' => 'audiomack.svg',
            'color' => '#ffa200',
            'text' => '#000000',
            'placeholder' => 'audiomack.com/username',
            'category' => 'music',
        ],
        // Developer Extended
        'leetcode' => [
            'name' => 'LeetCode',
            'icon' => 'leetcode.svg',
            'color' => '#FFA116',
            'text' => '#000000',
            'placeholder' => 'leetcode.com/u/...',
            'category' => 'developer',
        ],
        'hackerrank' => [
            'name' => 'HackerRank',
            'icon' => 'hackerrank.svg',
            'color' => '#1ba94c',
            'text' => '#ffffff',
            'placeholder' => 'hackerrank.com/username',
            'category' => 'developer',
        ],
        'codepen' => [
            'name' => 'CodePen',
            'icon' => 'codepen.svg',
            'color' => '#000000',
            'text' => '#ffffff',
            'placeholder' => 'codepen.io/username',
            'category' => 'developer',
        ],
        'codeberg' => [
            'name' => 'Codeberg',
            'icon' => 'codeberg.svg',
            'color' => '#2185D0',
            'text' => '#ffffff',
            'placeholder' => 'codeberg.org/username',
            'category' => 'developer',
        ],
        'matrix' => [
            'name' => 'Matrix',
            'icon' => 'matrix.svg',
            'color' => '#000000',
            'text' => '#ffffff',
            'placeholder' => 'matrix.to/#/@user:server',
            'category' => 'developer',
        ],
        // Social Extended
        'bereal' => [
            'name' => 'BeReal',
            'icon' => 'bereal.svg',
            'color' => '#000000',
            'text' => '#ffffff',
            'placeholder' => 'bfrg.it/...',
            'category' => 'social',
        ],
        'lemmy' => [
            'name' => 'Lemmy',
            'icon' => 'lemmy.svg',
            'color' => '#00bc8c',
            'text' => '#ffffff',
            'placeholder' => 'lemmy.world/u/...',
            'category' => 'social',
        ],
        'pixelfed' => [
            'name' => 'Pixelfed',
            'icon' => 'pixelfed.svg',
            'color' => '#f08ca8',
            'text' => '#ffffff',
            'placeholder' => 'pixelfed.social/...',
            'category' => 'social',
        ],
        'nostr' => [
            'name' => 'Nostr',
            'icon' => 'nostr.svg',
            'color' => '#8e30eb',
            'text' => '#ffffff',
            'placeholder' => 'npub...',
            'category' => 'social',
        ],
        'spacehey' => [
            'name' => 'SpaceHey',
            'icon' => 'spacehey.svg',
            'color' => '#f76203',
            'text' => '#ffffff',
            'placeholder' => 'spacehey.com/profile?id=...',
            'category' => 'social',
        ],
        'vero' => [
            'name' => 'Vero',
            'icon' => 'vero.svg',
            'color' => '#1b1b1b',
            'text' => '#ffffff',
            'placeholder' => 'vero.co/username',
            'category' => 'social',
        ],
        // Entertainment Extended
        'myanimelist' => [
            'name' => 'MyAnimeList',
            'icon' => 'myanimelist.svg',
            'color' => '#2E51A2',
            'text' => '#ffffff',
            'placeholder' => 'myanimelist.net/profile/...',
            'category' => 'entertainment',
        ],
        'anilist' => [
            'name' => 'AniList',
            'icon' => 'anilist.svg',
            'color' => '#02A9FF',
            'text' => '#ffffff',
            'placeholder' => 'anilist.co/user/...',
            'category' => 'entertainment',
        ],
        'trakt' => [
            'name' => 'Trakt',
            'icon' => 'trakt.svg',
            'color' => '#ed1c24',
            'text' => '#ffffff',
            'placeholder' => 'trakt.tv/users/...',
            'category' => 'entertainment',
        ],
        // Messaging Extended
        'viber' => [
            'name' => 'Viber',
            'icon' => 'viber.svg',
            'color' => '#665CAC',
            'text' => '#ffffff',
            'placeholder' => 'viber://chat?number=...',
            'category' => 'messaging',
        ],
        'keybase' => [
            'name' => 'Keybase',
            'icon' => 'keybase.svg',
            'color' => '#FF6F21',
            'text' => '#ffffff',
            'placeholder' => 'keybase.io/username',
            'category' => 'messaging',
        ],
        'simplex' => [
            'name' => 'SimpleX',
            'icon' => 'simplex.svg',
            'color' => '#2688e4',
            'text' => '#ffffff',
            'placeholder' => 'simplex.chat/contact/...',
            'category' => 'messaging',
        ],
        // Business Extended
        'gumroad' => [
            'name' => 'Gumroad',
            'icon' => 'gumroad.svg',
            'color' => '#ff90e8',
            'text' => '#000000',
            'placeholder' => 'username.gumroad.com',
            'category' => 'shopping',
        ],
        'redbubble' => [
            'name' => 'Redbubble',
            'icon' => 'redbubble.svg',
            'color' => '#d41324',
            'text' => '#ffffff',
            'placeholder' => 'redbubble.com/people/...',
            'category' => 'shopping',
        ],
        'upwork' => [
            'name' => 'Upwork',
            'icon' => 'upwork.svg',
            'color' => '#14a800',
            'text' => '#ffffff',
            'placeholder' => 'upwork.com/freelancers/...',
            'category' => 'shopping',
        ],
        'revolut' => [
            'name' => 'Revolut',
            'icon' => 'revolut.svg',
            'color' => '#000000',
            'text' => '#ffffff',
            'placeholder' => 'revolut.me/...',
            'category' => 'payment',
        ],
        // Web3/Crypto Extended
        'opensea' => [
            'name' => 'OpenSea',
            'icon' => 'opensea.svg',
            'color' => '#2081e2',
            'text' => '#ffffff',
            'placeholder' => 'opensea.io/username',
            'category' => 'design',
        ],
        // Professional Extended
        'xing' => [
            'name' => 'XING',
            'icon' => 'xing.svg',
            'color' => '#006567',
            'text' => '#ffffff',
            'placeholder' => 'xing.com/profile/...',
            'category' => 'social',
        ],
        'researchgate' => [
            'name' => 'ResearchGate',
            'icon' => 'researchgate.svg',
            'color' => '#00ccbb',
            'text' => '#ffffff',
            'placeholder' => 'researchgate.net/profile/...',
            'category' => 'developer',
        ],
        'orcid' => [
            'name' => 'ORCID',
            'icon' => 'orcid.svg',
            'color' => '#A6CE39',
            'text' => '#ffffff',
            'placeholder' => 'orcid.org/0000-...',
            'category' => 'developer',
        ],
        // Other Extended
        'clubhouse' => [
            'name' => 'Clubhouse',
            'icon' => 'clubhouse.svg',
            'color' => '#F2E8D9',
            'text' => '#000000',
            'placeholder' => 'clubhouse.com/@...',
            'category' => 'social',
        ],
        'guilded' => [
            'name' => 'Guilded',
            'icon' => 'guilded.svg',
            'color' => '#F5C400',
            'text' => '#000000',
            'placeholder' => 'guilded.gg/...',
            'category' => 'messaging',
        ],
        'cameo' => [
            'name' => 'Cameo',
            'icon' => 'cameo.svg',
            'color' => '#00c3c4',
            'text' => '#ffffff',
            'placeholder' => 'cameo.com/...',
            'category' => 'entertainment',
        ],
        'ngl' => [
            'name' => 'NGL',
            'icon' => 'ngl.svg',
            'color' => '#FF4136',
            'text' => '#ffffff',
            'placeholder' => 'ngl.link/...',
            'category' => 'social',
        ],
    ],
    // Categories for organizing platforms
    'categories' => [
        'social' => 'Social Media',
        'messaging' => 'Messaging',
        'music' => 'Music & Podcast',
        'video' => 'Video & Streaming',
        'developer' => 'Developer',
        'design' => 'Design & Creative',
        'shopping' => 'Shopping & Business',
        'payment' => 'Payment & Support',
        'productivity' => 'Productivity',
        'gaming' => 'Gaming',
        'entertainment' => 'Entertainment',
        'appstore' => 'App Stores',
        'contact' => 'Contact',
        'generic' => 'Generic',
    ],
    // Button shapes
    'shapes' => [
        'rounded' => ['label' => 'Rounded', 'radius' => '12px'],
        'pill' => ['label' => 'Pill', 'radius' => '9999px'],
        'square' => ['label' => 'Square', 'radius' => '4px'],
        'none' => ['label' => 'None', 'radius' => '0'],
    ],
    // Button shadows
    'shadows' => [
        'none' => ['label' => 'None', 'value' => 'none'],
        'sm' => ['label' => 'Small', 'value' => '0 1px 2px rgba(0,0,0,0.05)'],
        'md' => ['label' => 'Medium', 'value' => '0 4px 6px -1px rgba(0,0,0,0.1)'],
        'lg' => ['label' => 'Large', 'value' => '0 10px 15px -3px rgba(0,0,0,0.1)'],
        'xl' => ['label' => 'Extra Large', 'value' => '0 20px 25px -5px rgba(0,0,0,0.1)'],
    ],
    // Theme presets
    'themes' => [
        'light' => [
            'name' => 'Light',
            'background' => '#ffffff',
            'card_bg' => 'transparent',
            'text' => '#1e293b',
            'bio' => '#64748b',
            'link_bg' => '#f1f5f9',
            'link_text' => '#1e293b',
        ],
        'dark' => [
            'name' => 'Dark',
            'background' => '#0f172a',
            'card_bg' => 'transparent',
            'text' => '#f1f5f9',
            'bio' => '#94a3b8',
            'link_bg' => '#1e293b',
            'link_text' => '#f1f5f9',
        ],
        'midnight' => [
            'name' => 'Midnight',
            'background' => 'linear-gradient(135deg, #1e293b 0%, #0f172a 100%)',
            'card_bg' => 'rgba(30, 41, 59, 0.5)',
            'text' => '#f1f5f9',
            'bio' => '#94a3b8',
            'link_bg' => 'rgba(51, 65, 85, 0.9)',
            'link_text' => '#f1f5f9',
        ],
        'sunset' => [
            'name' => 'Sunset',
            'background' => 'linear-gradient(135deg, #f97316 0%, #ec4899 100%)',
            'card_bg' => 'rgba(255, 255, 255, 0.9)',
            'text' => '#1e293b',
            'bio' => '#64748b',
            'link_bg' => '#ffffff',
            'link_text' => '#1e293b',
        ],
        'ocean' => [
            'name' => 'Ocean',
            'background' => 'linear-gradient(135deg, #0ea5e9 0%, #6366f1 100%)',
            'card_bg' => 'rgba(255, 255, 255, 0.9)',
            'text' => '#1e293b',
            'bio' => '#64748b',
            'link_bg' => '#ffffff',
            'link_text' => '#1e293b',
        ],
        'forest' => [
            'name' => 'Forest',
            'background' => 'linear-gradient(135deg, #22c55e 0%, #15803d 100%)',
            'card_bg' => 'rgba(255, 255, 255, 0.9)',
            'text' => '#1e293b',
            'bio' => '#64748b',
            'link_bg' => '#ffffff',
            'link_text' => '#1e293b',
        ],
        'purple-haze' => [
            'name' => 'Purple Haze',
            'background' => 'linear-gradient(135deg, #8b5cf6 0%, #d946ef 100%)',
            'card_bg' => 'rgba(255, 255, 255, 0.95)',
            'text' => '#1e293b',
            'bio' => '#64748b',
            'link_bg' => '#ffffff',
            'link_text' => '#1e293b',
        ],
        'minimal' => [
            'name' => 'Minimal',
            'background' => '#fafafa',
            'card_bg' => 'transparent',
            'text' => '#18181b',
            'bio' => '#71717a',
            'link_bg' => '#ffffff',
            'link_text' => '#18181b',
            'link_border' => '#e4e4e7',
        ],
        'mono' => [
            'name' => 'Mono',
            'description' => 'Terminal-style monospace theme',
            'background' => '#1a1a1a',
            'card_bg' => 'transparent',
            'text' => '#00ff00',
            'bio' => '#00cc00',
            'link_bg' => 'transparent',
            'link_text' => '#00ff00',
            'link_border' => '#00ff00',
            'font_family' => "'Courier New', monospace",
        ],
        'galaxy' => [
            'name' => 'Galaxy',
            'description' => 'Parallax starfield animation',
            'background' => 'linear-gradient(135deg, #0c0c1e 0%, #1a1a3e 50%, #0c0c1e 100%)',
            'card_bg' => 'transparent',
            'text' => '#ffffff',
            'bio' => '#c0c0c0',
            'link_bg' => 'rgba(255, 255, 255, 0.1)',
            'link_text' => '#ffffff',
            'link_border' => 'rgba(255, 255, 255, 0.3)',
            'has_animation' => true,
        ],
        'stargazer' => [
            'name' => 'Stargazer',
            'description' => 'Animated star background',
            'background' => 'linear-gradient(135deg, #0f0f23 0%, #1a1a3e 100%)',
            'card_bg' => 'transparent',
            'text' => '#ffd700',
            'bio' => '#e0e0e0',
            'link_bg' => 'rgba(255, 215, 0, 0.1)',
            'link_text' => '#ffd700',
            'link_border' => '#ffd700',
            'has_animation' => true,
        ],
        'magic-kingdom' => [
            'name' => 'Magic Kingdom',
            'description' => 'Esthetic purple theme',
            'background' => 'linear-gradient(135deg, #2d1b4e 0%, #1a0f2e 100%)',
            'card_bg' => 'transparent',
            'text' => '#e0b0ff',
            'bio' => '#c0a0d0',
            'link_bg' => 'rgba(224, 176, 255, 0.1)',
            'link_text' => '#e0b0ff',
            'link_border' => 'rgba(224, 176, 255, 0.5)',
            'has_animation' => true,
        ],
        'flare' => [
            'name' => 'Flare',
            'description' => 'Bright warm colors',
            'background' => 'linear-gradient(135deg, #ff6b35 0%, #f7931e 100%)',
            'card_bg' => 'rgba(255, 255, 255, 0.95)',
            'text' => '#1e293b',
            'bio' => '#64748b',
            'link_bg' => '#ffffff',
            'link_text' => '#ff6b35',
        ],
        'sublime' => [
            'name' => 'Sublime',
            'description' => 'Cool blue minimalist',
            'background' => 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
            'card_bg' => 'rgba(255, 255, 255, 0.95)',
            'text' => '#1e293b',
            'bio' => '#64748b',
            'link_bg' => '#ffffff',
            'link_text' => '#667eea',
        ],
        'dawn' => [
            'name' => 'Dawn',
            'description' => 'Soft sunrise colors',
            'background' => 'linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%)',
            'card_bg' => 'rgba(255, 255, 255, 0.9)',
            'text' => '#5c4033',
            'bio' => '#8b6914',
            'link_bg' => 'rgba(255, 255, 255, 0.8)',
            'link_text' => '#5c4033',
        ],
        'aurora' => [
            'name' => 'Aurora',
            'description' => 'Northern lights gradient',
            'background' => 'linear-gradient(135deg, #00c6fb 0%, #005bea 50%, #7c3aed 100%)',
            'card_bg' => 'rgba(255, 255, 255, 0.9)',
            'text' => '#1e293b',
            'bio' => '#64748b',
            'link_bg' => 'rgba(255, 255, 255, 0.9)',
            'link_text' => '#1e293b',
        ],
        'misty-rain' => [
            'name' => 'Misty Rain',
            'description' => 'Serene rain backdrop',
            'background' => 'linear-gradient(135deg, #373b44 0%, #4286f4 100%)',
            'card_bg' => 'transparent',
            'text' => '#ffffff',
            'bio' => '#c0d0e0',
            'link_bg' => 'rgba(255, 255, 255, 0.1)',
            'link_text' => '#ffffff',
            'link_border' => 'rgba(255, 255, 255, 0.3)',
            'has_animation' => true,
        ],
        'cloudy-storm' => [
            'name' => 'Cloudy Storm',
            'description' => 'Animated thunderstorm',
            'background' => 'linear-gradient(135deg, #1f1c2c 0%, #928dab 100%)',
            'card_bg' => 'transparent',
            'text' => '#ffffff',
            'bio' => '#c0c0c0',
            'link_bg' => 'rgba(255, 255, 255, 0.15)',
            'link_text' => '#ffffff',
            'link_border' => 'rgba(255, 255, 255, 0.4)',
            'has_animation' => true,
        ],
        'rainbow' => [
            'name' => 'Rainbow',
            'description' => 'Colorful animated theme',
            'background' => 'linear-gradient(90deg, #ff0000, #ff7f00, #ffff00, #00ff00, #0000ff, #4b0082, #8b00ff)',
            'card_bg' => 'rgba(255, 255, 255, 0.95)',
            'text' => '#1e293b',
            'bio' => '#64748b',
            'link_bg' => '#ffffff',
            'link_text' => '#1e293b',
            'has_animation' => true,
        ],
        'winter-wonderland' => [
            'name' => 'Winter Wonderland',
            'description' => 'Snowy winter theme',
            'background' => 'linear-gradient(135deg, #e0f7fa 0%, #b2ebf2 100%)',
            'card_bg' => 'rgba(255, 255, 255, 0.9)',
            'text' => '#37474f',
            'bio' => '#607d8b',
            'link_bg' => 'rgba(255, 255, 255, 0.95)',
            'link_text' => '#37474f',
            'has_animation' => true,
        ],
        // Cyberpunk / Neon themes
        'neon-city' => [
            'name' => 'Neon City',
            'description' => 'Cyberpunk neon glow',
            'background' => '#0a0a0f',
            'card_bg' => 'transparent',
            'text' => '#ff00ff',
            'bio' => '#00ffff',
            'link_bg' => 'transparent',
            'link_text' => '#ff00ff',
            'link_border' => '#00ffff',
            'link_shadow' => '0 0 10px #ff00ff, 0 0 20px #00ffff',
        ],
        'retrowave' => [
            'name' => 'Retrowave',
            'description' => '80s synthwave aesthetic',
            'background' => 'linear-gradient(180deg, #0c0c1e 0%, #1a0a2e 50%, #2d0b3e 100%)',
            'card_bg' => 'transparent',
            'text' => '#ff6ec7',
            'bio' => '#7b68ee',
            'link_bg' => 'rgba(255, 110, 199, 0.1)',
            'link_text' => '#ff6ec7',
            'link_border' => '#ff6ec7',
        ],
        'matrix' => [
            'name' => 'Matrix',
            'description' => 'Green code rain effect',
            'background' => '#000000',
            'card_bg' => 'transparent',
            'text' => '#00ff41',
            'bio' => '#00cc33',
            'link_bg' => 'rgba(0, 255, 65, 0.1)',
            'link_text' => '#00ff41',
            'link_border' => '#00ff41',
            'has_animation' => true,
        ],
        // Nature themes
        'cherry-blossom' => [
            'name' => 'Cherry Blossom',
            'description' => 'Japanese sakura theme',
            'background' => 'linear-gradient(135deg, #ffeef8 0%, #ffe4ec 100%)',
            'card_bg' => 'rgba(255, 255, 255, 0.8)',
            'text' => '#8b5a5a',
            'bio' => '#c48b9f',
            'link_bg' => 'rgba(255, 183, 197, 0.3)',
            'link_text' => '#8b5a5a',
        ],
        'deep-sea' => [
            'name' => 'Deep Sea',
            'description' => 'Ocean depths gradient',
            'background' => 'linear-gradient(135deg, #001e3c 0%, #0d47a1 100%)',
            'card_bg' => 'transparent',
            'text' => '#81d4fa',
            'bio' => '#4fc3f7',
            'link_bg' => 'rgba(129, 212, 250, 0.1)',
            'link_text' => '#81d4fa',
            'link_border' => 'rgba(129, 212, 250, 0.5)',
        ],
        'tropical' => [
            'name' => 'Tropical',
            'description' => 'Vibrant tropical vibes',
            'background' => 'linear-gradient(135deg, #11998e 0%, #38ef7d 100%)',
            'card_bg' => 'rgba(255, 255, 255, 0.95)',
            'text' => '#1e293b',
            'bio' => '#64748b',
            'link_bg' => '#ffffff',
            'link_text' => '#11998e',
        ],
        // Minimalist themes
        'paper' => [
            'name' => 'Paper',
            'description' => 'Clean paper texture',
            'background' => '#f5f5dc',
            'card_bg' => '#fffef0',
            'text' => '#333333',
            'bio' => '#666666',
            'link_bg' => '#ffffff',
            'link_text' => '#333333',
            'link_border' => '#cccccc',
        ],
        'ink' => [
            'name' => 'Ink',
            'description' => 'Dark with white accents',
            'background' => '#1a1a1a',
            'card_bg' => 'transparent',
            'text' => '#ffffff',
            'bio' => '#999999',
            'link_bg' => 'transparent',
            'link_text' => '#ffffff',
            'link_border' => '#ffffff',
        ],
        'glass' => [
            'name' => 'Glass',
            'description' => 'Glassmorphism effect',
            'background' => 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
            'card_bg' => 'rgba(255, 255, 255, 0.15)',
            'text' => '#ffffff',
            'bio' => '#e0e0e0',
            'link_bg' => 'rgba(255, 255, 255, 0.2)',
            'link_text' => '#ffffff',
            'link_border' => 'rgba(255, 255, 255, 0.3)',
            'link_backdrop_blur' => '10px',
        ],
        'clay' => [
            'name' => 'Clay',
            'description' => 'Soft 3D clay morphism',
            'background' => '#e0e5ec',
            'card_bg' => '#e0e5ec',
            'text' => '#333333',
            'bio' => '#666666',
            'link_bg' => '#e0e5ec',
            'link_text' => '#333333',
            'link_shadow' => '5px 5px 10px #b8bec5, -5px -5px 10px #ffffff',
        ],
    ],
];
